project_id = "yowjsupwecwzyrkphtvv"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.confirm-delivery]
verify_jwt = false

[functions.admin-override-confirmation]
verify_jwt = false
